### ISSUE TITLE
Service.yml is not good

### ISSUE THREAD

**Issue by lyrixx** [PHPFastCGI/SpeedfonyBundle#2]
I followed http://phpfastcgi.github.io/general/2015/07/14/making-symfony-faster.html

and 

```
[Symfony\Component\Debug\Exception\ContextErrorException] 

Catchable Fatal Error: Argument 2 passed to PHPFastCGI\FastCGIDaemon\Command\DaemonRunCommand::__construct() must be an instance of PHPFastCGI\FastCGIDaemon\Driver \DriverContainerInterface, null given, called in /home/greg/dev/github.com/blackfireio/blackfire.io/app/cache/dev/appDevDebugProjectContainer.php on line 5229 and defined
```

That does not work

**Comment by AndrewCarterUK** [comment]
Hello Gregoire,

Thank you for letting me know, I'm out at the moment but will publish a fix
as soon as I'm back in a few hours.

**Comment by AndrewCarterUK** [comment]
@lyrixx - Thank you very much for reporting this. The error was caused be me failing to update the configuration file to reflect changes that had been made to the structure of the core - I'm very sorry!

I got the same error as you, but I believe it should now be fixed. I've tagged the release as v0.7.1, so a composer update should fix this for you.

Please let me know if you have any further issues :)
